### ISSUE TITLE
When using 'gridrec' algorithm for reconstruction, I get an error: 'Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)'

### ISSUE THREAD

**Issue by antimatter874** [tomopy/tomopy#464] opened 2020-02-12 00:39 UTC
When I run the reconstruction function, Tomopy.recon, using the 'gridrec' algorithm, I get an error:'Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)'
This error does not arise when using other algorithms, like 'art'.

**To Reproduce (if applicable)**

images are obtained from the paper: https://www.science-on-stage.eu/images/download/tmom_michalis_orfanakis_optical_ct_scanner_greece.pdf
images are available from google drive: https://goo.gl/Mffb1m  (Data Sets/ Lego Red Gummy 20_06_17)

```python
theta = np.arange(0, 2 * np.pi, 2 * (np.pi / 180))
reconstructed = tomopy.recon(images, theta, algorithm='gridrec') #images is a ndarray (180, 480, 640) i.e. 180 projection (480x640) images 


**Platform Information:**
 - OS: macOS 10.15.3 Catalina
 - Python Version 3.7
 - TomoPy Version 1.7.0

**Comment by carterbox** [comment] 2020-02-12 16:43
This is a duplicate of #436

**Closed** 2020-02-12 16:45 UTC
Labels: bug, duplicate, macOS
