### ISSUE TITLE
gridrec Segmentation fault: 11

### ISSUE THREAD

**Issue by maximka48** [tomopy/tomopy#407] opened 2019-05-06 15:19 UTC
Hi

I updated to the version 1.4.1 of tomopy and experienced problems with gridrec. It doesn't work, looks like it crushes kernel, giving 'Segmentation fault: 11'. Not sure what it means, as I couldn't find it in the code.
All other reconstruction algorithms work successfully. 
The same code and same dataset also works successfully with gridrec on tomopy 1.1.2.
What could be the problem?

I use macOS, I attach here versions of my packages installed, in case it helps:
alabaster                 0.7.12                   py37_0  
appnope                   0.1.0                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.2.5                    py37_0  
attrs                     19.1.0                   py37_1  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
bleach                    3.1.0                    py37_0  
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.1.23                     0  
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2019.3.9                 py37_0  
cffi                      1.12.3           py37hb5b8e2f_0  
cftime                    1.0.3.4         py37h917ab60_1000    conda-forge
chardet                   3.0.4                    py37_1  
cloudpickle               0.8.1                      py_0  
cryptography              2.6.1            py37ha12b0ac_0  
curl                      7.62.0               ha441bb4_0  
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py37h470a237_1    conda-forge
dask-core                 1.2.1                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                      py_0  
docutils                  0.14                     py37_0  
dxchange                  0.1.5                 py37_1000    conda-forge
dxfile                    0.5                        py_1    conda-forge
edffile                   5.0.0           pyh24bf2e0_1000    conda-forge
entrypoints               0.3                      py37_0  
ffmpeg                    4.1.3                h5c2b479_0    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
gnutls                    3.6.5             h53004b3_1002    conda-forge
graphite2                 1.3.13            h2098e52_1000    conda-forge
h5py                      2.9.0           nompi_py37h35dc34b_1102    conda-forge
harfbuzz                  2.4.0                h92b87b8_0    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                      py37_0  
imageio                   2.5.0                    py37_0    conda-forge
imagesize                 1.1.0                    py37_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.5.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
isort                     4.3.17                   py37_0  
jasper                    1.900.1           h636a363_1006    conda-forge
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
joblib                    0.13.2                   py37_0  
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.1                    py37_0  
jupyter_client            5.2.4                    py37_0  
jupyter_core              4.4.0                    py37_0  
keyring                   18.0.0                   py37_0  
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
lame                      3.100             h1de35cc_1001    conda-forge
lazy-object-proxy         1.3.1            py37h1de35cc_2  
libblas                   3.8.0                8_openblas    conda-forge
libcblas                  3.8.0                8_openblas    conda-forge
libcurl                   7.62.0               h051b688_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0                8_openblas    conda-forge
liblapacke                3.8.0                8_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h79f4b77_1001    conda-forge
libwebp                   1.0.2                h14d73da_2    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib-base           3.0.3            py37habd5b94_1    conda-forge
maximus48                 0.3.3                     <pip>
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.3                      199  
mkl_fft                   1.0.12           py37h01d97ff_1    conda-forge
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
netcdf4                   1.5.1.1          py37h58b02fa_0    conda-forge
nettle                    3.4.1             h3efe00b_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numexpr                   2.6.9           py37h1702cab_1000    conda-forge
numpy                     1.16.3           py37hdf140aa_0    conda-forge
numpydoc                  0.9.1                      py_0  
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.6                hd44dcd8_1    conda-forge
opencv                    4.1.0            py37h0cb0d9f_1    conda-forge
openh264                  1.8.0             hd9629dc_1000    conda-forge
openssl                   1.1.1b               h1de35cc_1  
packaging                 19.0                     py37_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.4.0                      py_0  
pcre                      8.41              h0a44026_1003    conda-forge
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0           py37hbddbef0_1000    conda-forge
pip                       19.1                     py37_0  
pixman                    0.34.0            h1de35cc_1003    conda-forge
prompt_toolkit            2.0.9                    py37_0  
psutil                    5.6.2            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
pycodestyle               2.5.0                    py37_0  
pycparser                 2.19                     py37_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.3.1                    py37_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0            py37h655552a_6  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.3                h359304d_0  
python-dateutil           2.8.0                      py_0    conda-forge
python.app                2                        py37_9  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py37h1e5eb4f_1    conda-forge
pyzmq                     18.0.0           py37h0a44026_0  
qt                        5.6.3                h1d42b2f_0  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.7.0                    py37_1  
readline                  7.0                  h1de35cc_5  
requests                  2.21.0                   py37_0  
rope                      0.14.0                     py_0  
scikit-image              0.15.0           py37h6de7cb9_0    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                41.0.1                   py37_0  
sip                       4.18.1           py37h0a44026_2  
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                    py37_0  
spefile                   1.6                        py_1    conda-forge
sphinx                    2.0.1                      py_0  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
spyder                    3.3.4                    py37_0  
spyder-kernels            0.4.4                    py37_0  
sqlite                    3.28.0               ha441bb4_0  
testpath                  0.4.2                    py37_0  
tifffile                  0.15.1          py37h917ab60_1001    conda-forge
tk                        8.6.8                ha441bb4_0  
tomopy                    1.4.1            py37h01d97ff_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.1                   py37_0  
wrapt                     1.11.1           py37h1de35cc_0  
wurlitzer                 1.0.2                    py37_0  
x264                      1!152.20180806       h1de35cc_0    conda-forge
xz                        5.2.4                h1de35cc_4  
zeromq                    4.3.1                h0a44026_3  
zlib                      1.2.11               h1de35cc_3

**Comment by dgursoy** [comment] 2019-05-06 15:23
Thanks. Could you also please share your script? Have you tried a basic reconstruction test like below?

```
import tomopy

obj = tomopy.lena(100)
ang = tomopy.angles(180)
prj = tomopy.project(obj, ang)
rec = tomopy.recon(prj, ang, algorithm='gridrec')
```

**Comment by maximka48** [comment] 2019-05-07 12:02
Thanks for your answer. Your basic test didn't work for the first time, but worked for the second time. After that, my code started to work as well. I didn't touch anything else, so this is anyway strange. But somehow the error doesn't appear at the moment, even after rebooting python.

'''import tomopy
import matplotlib.pyplot as plt
import numpy as np

proj = np.load('data_w10.npy')

N_steps = 1
n = proj.shape[0]
angle = np.pi*np.arange(n)/(N_steps*180) 

cent = 1182.64
recon = tomopy.recon(proj, angle, center = cent, algorithm = 'gridrec')
plt.imshow(recon[0], cmap='gray')
'''

I attach the data as well.
https://oc.embl.de/index.php/s/KStBnABJCskqTAm

**Comment by jrmadsen** [comment] 2019-05-07 18:51
I have seen a similar problem but forgot about it. I ran it through at a debugger at some point and there was nothing obvious in TomoPy's code and I was pretty sure it was something happening in MKL. Are you using the same conda environment (i.e. same MKL version) for the TomoPy version with gridrec that worked?

**Comment by dgursoy** [comment] 2019-05-07 19:48
I couldn't reproduce the problem with the data that you provided, butI haven't checked with your Python environment. Since the problem seems to be solved magically, I'll close this issue. We can re-open this thread if it happens again.

**Closed by dgursoy** 2019-05-07 19:48 UTC

**Comment by jrmadsen** [comment] 2019-05-07 21:07
Which python version were you using @dgursoy? It looks like above was 3.7 but I think your inability to reproduce it supports the theory that the issue is external to TomoPy.

**Comment by maximka48** [comment] 2019-05-08 10:46
Hi @jrmadsen. The gridrec that worked was on different conda environment with python 3.5. and older  versions for all packages. I believe that the problem is indeed in MKL or numpy, as I have seen it already yesterday once without using tomopy.  
Thank you @dgursoy . I also can't reproduce the error at the moment, but will write here in case it will appear in a more systematic way.
