### ISSUE TITLE
mproc issue

### ISSUE THREAD

**Issue by xianghuix** [tomopy/tomopy#136] opened 2015-12-02 20:24 UTC
The mproc.py in current version has some issues. It does not parallelize computations to multiple CPU cores. I changed it back to the old implementation back to 2015-05-23 then I can get all cores loaded. Please test the code before a new release is published. I heard few groups experiencing the same issues with the latest version.

**Comment by dgursoy** [comment] 2015-12-03 02:58
Also noted that and looking into this.

**Comment by dgursoy** [comment] 2015-12-05 15:33
I couldn't reproduce the problem and need more info to dig into the problem? Can you write which platform, script, data, etc. did you use?

**Comment by xianghuix** [comment] 2015-12-05 19:42
Redhat 6.7; tomopy updated just two days before the issue report. did zinger removal and few other filterings. all were slow because only single core was used.
________________________________________

**Comment by dgursoy** [comment] 2015-12-05 20:33
I understand what the issue is. I can look into that if you send me the script, tomopy version, and the data path (assuming the data is at Petrel).

**Comment by xianghuix** [comment] 2015-12-05 21:05
tomopy version 0.1.11.

example code

************************
import tomopy 
import os
import numpy as np
from tomopy.recon.rotation import write_center
from tomopy.recon.algorithm import recon
from scipy import misc

data, white, dark = tomopy.io.exchange.read_aps_2bm(file_name,sino=(700,720,1))
data_size = data.shape
theta = np.linspace(0,np.pi,num=data_size[0])

data = tomopy.misc.corr.remove_outlier(data,zinger_level,size=15,axis=0)
************************

data should not matter. it can read data successfully. you can use any real data set from APS to test.
________________________________________

**Comment by dgursoy** [comment] 2015-12-05 21:30
I checked the following code with my Mac and multiprocessing seems to be working correctly. I'll try also with a Linux machine and a standard 2BM data and let you know:
```
import tomopy

obj = tomopy.lena(2048)
ang = tomopy.angles(1500)
prj = tomopy.project(obj, ang)
prj = tomopy.remove_outlier(prj, 10, size=15, axis=0)
```

**Comment by dgursoy** [comment] 2015-12-05 22:54
I think this is resolved with the new version 0.1.12. Could you give it a try?

**Comment by decarlof** [comment] 2015-12-06 01:39
can you share the script you were using? thanks
f

**Comment by xianghuix** [comment] 2015-12-09 00:48
I tried latest version 0.1.12 and the problem is indeed gone. Thank you very much.


________________________________

**Comment by dgursoy** [comment] 2015-12-09 02:15
Nice!

**Closed by dgursoy** 2015-12-09 02:15 UTC
