### ISSUE TITLE
Problem compiling on win 10

### ISSUE THREAD

**Issue by PierFF** [tomopy/tomopy#556] opened 2021-09-14 09:51 UTC
Hi everyone

A question from a tomopy newbie :-)

I am trying to compile tomopy for the first time in order to be able to use the GPU version of the reconstruction algorithm.

First of I would be sure that I understood that correctly and that compilation is really mandatory in order to use GPU acceleration... can anyone please confirm this to me ?

Secondly, is this the right place to ask this kind of questions, or should I use a dedicated forum/chat/discord room .... I am not aware of ?

Concerning compilation problem, it arises during the configuring phase of cmake when executing python setup.py build,  and  I get a lot of errors of this type 

"CMake Error at source/PTL/cmake/Modules/MacroUtilities.cmake:887 (add_library):
  Target "ptl-static" links to target "CUDA::nppc_static" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  source/PTL/source/CMakeLists.txt:60 (build_library)"

cmake finds  the correct version of the CUDA SDK before giving this error and I have followed the instructions on the developer section in order to compile from sources.

I  am using 
- Miniconda with python 3.8.11
- cmake 3.19.6 (installed by conda)
- visual studio 2017
- cuda sdk 11.4 with (all packages installed including vs integration)

Anyone as an idea of what am I doing wrong ?

Thanks in advance,

Cheers,

Pier

**Comment by carterbox** [comment] 2021-09-14 16:51
Hi @PierFF,

> that compilation is really mandatory in order to use GPU acceleration... can anyone please confirm this to me ?

For Linux, you can install pre-built tomopy with CUDA using conda. For Windows, it is necessary until the conda-forge CUDA build tools for Windows improve.

> Secondly, is this the right place to ask this kind of questions, or should I use a dedicated forum/chat/discord room .... I am not aware of ?

This is the correct place.

> Anyone as an idea of what am I doing wrong ?

I have not yet compiled with CUDA 11.4 on Windows. I have a vague feeling that the NPPC library has been moved/renamed in CUDA 11, so that may be the cause of the problem.

I suggest using the `--disable-tasking` option when building to skip building the PTL module if that's where all the errors are coming from. Also, please include the full output of the build instead of only selected lines.

**Comment by jrmadsen** [comment] 2021-09-14 17:06
@carterbox you may be right that target is missing but given that PTL doesn't require linking to that CUDA target, I suspect that there is a variable name in tomopy's CMake that is propagating down in the PTL CMake and PTL is also using that variable and thus this particular issue might be fixed by renaming the variable used in the tomopy CMake to avoid the conflict.

**Comment by jrmadsen** [comment] 2021-09-14 17:09
If I remember correctly w.r.t. how I used to write CMake several years back, my guess is that variable might be named something along the lines of `EXTERNAL_LIBRARIES`

**Comment by carterbox** [comment] 2021-09-14 17:22
> there is a variable name in tomopy's CMake that is propagating down in the PTL CMake

@jrmadsen Yes, it does seem that `cmake/Modules/Packages.cmake` use the same variable names in both TomoPy and PTL. For variables such as `EXTERNAL_LIBRARIES`, `EXTERNAL_INCLUDE_DIRS`. I can prefix these with `TOMOPY_` to prevent them from conflicting with other packages.

**Comment by jrmadsen** [comment] 2021-09-14 20:48
You could do that but it's better to use interface libraries to carry around the list of include dirs, libs, etc. instead of storing them in variables. Interface libraries are just logical CMake libraries which store include dirs, libs, etc. and add those properties to another when it "links" to it

**Comment by PierFF** [comment] 2021-09-15 09:07
Thank you for the quick answer.
 The problem persists even with the --disable-tasking build option. I attach the full output when using the option to this message. [build-output.txt](https://github.com/tomopy/tomopy/files/7168596/build-output.txt)

I can eventually try  to downgrade to CUDA SDK 10 to check if the problem comes from CUDA SDK 11.

**Comment by PierFF** [comment] 2021-09-15 09:56
After testing I can confirm that the problem comes from CUDA SDK 11. I have tried using CUDA 10 and everything compiles fine.
Still I have a problem when using tomopy after performing setup.py build install.
I get the following error when importing tomopy
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tomopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\__init__.py", line 63, in <module>
    from tomopy.misc.corr import *
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\misc\corr.py", line 60, in <module>
    import tomopy.util.extern as extern
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\util\extern\__init__.py", line 83, in <module>
    from tomopy.util.extern.recon import *
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\util\extern\recon.py", line 56, in <module>
    from .accel import c_accel_mlem
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\util\extern\accel.py", line 63, in <module>
    LIB_TOMOPY_ACCEL = c_shared_lib("libtomopy-accel", error=False)
  File "D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\util\extern\__init__.py", line 67, in c_shared_lib
    return load_dll(sharedlib)
  File "D:\Miniconda3\envs\tomoGPU\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "D:\Miniconda3\envs\tomoGPU\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Miniconda3\envs\tomoGPU\lib\site-packages\tomopy-1.10.3-py3.8-win-amd64.egg\tomopy\util\extern\libtomopy-accel.dll' (or one of its dependencies). Try using the full path with constructor syntax.

I have checked that all libtomopy-accel.dll are accessible in the conda environment using the Dependencies software... any idea of where this comes from ?

**Comment by PierFF** [comment] 2021-09-15 13:22
Hi and thanks for the quick answers....
The --disable-tasking  option only removes some errors but do not solve the problem. The full output is here:
[output.txt](https://github.com/tomopy/tomopy/files/7170310/output.txt)
I also tried uninstalling CUDA SDK 11 and installing the 10.2 version but I end up with the same kind of errors....

I also have non reproducible results since I was able to fully compile just after the change of SDK version (with import errors when using the library) but compilation has become impossible again after executing a  setup clean step (this is why I have deleted the comments I had previously posted)

I will try to compile on another win10 PC to rule out any problem due to the specific configuration of the PC I am currently using

**Comment by PierFF** [comment] 2021-09-15 14:02
The output when the compilation succeeds is the following 
[path-working.txt](https://github.com/tomopy/tomopy/files/7170671/path-working.txt)
If I am not wrong the only thing changing when I close the prompt and open it again is the presence of the bin and linbnvvp CUDA directories in the PATH

**Comment by carterbox** [comment] 2021-09-15 15:34
@PierFF, please let us know if the patch in #558 solves the problem you reported.

**Comment by PierFF** [comment] 2021-09-15 16:17
It actually solves the problem !!!(I have used the win-build-update branch). If I am not wrong the problem was coming from the fact that the static versions of the CUDA libraries are not installed when the SDK is installed on windows.

**Closed** 2021-09-15 19:36 UTC
Labels: Windows, build
