### ISSUE TITLE
AttributeError while running reconstruction script 

### ISSUE THREAD

**Issue by aaronclaeys** [tomopy/tomopy#470] opened 2020-03-11 18:35 UTC
I am trying to run the Tomopy reconstruction script but an AttributeError shows up when I try to run it. I am not experienced with Python or coding, but I have tried adjusting parameters in the reconstruction script and have tried both Python 2.7 and 3 as well as different Tomopy versions, with no success. I am not sure if there is an issue with compatibility between versions or if it is the code itself. Any help would be appreciated.

I've attached the traceback from the error. Let me know if more information is needed to help me with this issue. Thanks.

```python
Traceback (most recent call last):
  File "Aaron1.py", line 503, in <module>
    **loopEngineParams)           
  File "Aaron1.py", line 310, in loopEngine
    data = generalFilterContainer(data,**kwargs)   
  File "Aaron1.py", line 169, in generalFilterContainer
    data = tomopy.prep.stripe.remove_stripe_ti(data,**params)
  File "/home/rtguser/anaconda2/lib/python2.7/site-packages/tomopy/prep/stripe.py", line 228, in remove_stripe_ti
    nchunk=nchunk)
  File "/home/rtguser/anaconda2/lib/python2.7/site-packages/tomopy/util/mproc.py", line 163, in distribute_jobs
    arr_shared = as_sharedmem(arr)
  File "/home/rtguser/anaconda2/lib/python2.7/site-packages/tomopy/util/dtype.py", line 145, in as_sharedmem
    ctype = np.ctypeslib._typecodes[arr.__array_interface__['typestr']]
AttributeError: 'module' object has no attribute '_typecodes'
```

**Platform Information:**
 - OS: Linux
 - Python Version 2.7
 - TomoPy Version 1.0.0

**Additional context**
Aaron1.py is the renamed reconstruction script.

**Comment by carterbox** [comment] 2020-03-11 19:16
Hi @aaronclaeys, this is a duplicate of #392. Please update to `tomopy>=1.4.1` to obtain the patch which fixes this issue. Also, please note that Python 2 reached end of life at the beginning of this year and is no longer supported.

**Closed by carterbox** 2020-03-11 19:16 UTC
Labels: question
