### ISSUE TITLE
Wrap build system in mock Extension in order to configure from setup.cfg

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#361] opened 2018-11-05 03:04 UTC
@jrmadsen reports in #355, that `libtomopy.*` is not installed to `__site_packages__` when `tomopy` is installed by calling `python setup.py install`. However, installation using `pip` does copy the library. This should not be happening because `libtomopy.*` is included in `MANIFEST.in` which determines which files are included in the distributed package.

**Comment by newville** [comment] 2018-11-05 13:01
@carterbox @jrmadsen  Hm, I agree that `python setup.py install` should install the shared library. It does for me.  I wonder if it might be some confusion about where things get installed.

With th master branch, `python build.py && python setup.py install` installs to 
`.../site-packages/tomopy-1.2.1-py3.6.egg` and the shared library is put in `.../site-packages/tomopy-1.2.1-py3.6.egg/tomopy/sharedlibs/`.  And everything should work fine (that is, tests pass).

OTOH, if you do `python build.py && pip install .` in the same folder, tomopy gets installed to `.../site-packages/tomopy` and there is an associated  `.../site-packages/tomopy-1.2.1.dist-info`.  And `pip` *should* remove the `tomopy-1.2.1-py3.6.egg` because `pip` is "very clever".   The shared library will be installed properly and everything should work fine.   

However:  if you were to do `python setup.py install` *after* a `pip install`,  that `.../site-package/tomopy` folder from the earlier `pip install` will remain.  And that will be the one found when you import tomopy.  

I don't know about you all, but we see this problem frequently during development.  You may need to check the version of `tomopy` and remove other versions, especially `.../site-packages/tomopy` installed by an earlier `pip install`.

**Comment by carterbox** [comment] 2018-11-05 19:55
@newville I agree with your observations. `pip` is the smarter installer, so it knows when a package is already installed via `python setup.py install`. `setup.py` is a dumb installer which will rebuild and copy files to `site-packages` regardless of whether the packages is already installed. Both will successfully copy `libtomopy.*` to `site-packages` on Linux.

@jrmadsen Please confirm whether or not `libtomopy.*` is copied to `site-packages`. Maybe try removing `build` before you run `setup.py`. I think I read somewhere that this can interfere with using the correct `MANIFEST.in`.

**Comment by jrmadsen** [comment] 2018-11-05 20:39
Ok so I figured out where the "problem" is -- we were talking about two different situations. If you simply add:

```python
import subprocess as sp
sp.check_call((sys.executable, 'build.py'))
```
to the beginning of `setup.py` then `python setup.py install` installs correctly. This is perfectly inline with what I was saying earlier about `libtomopy.<ext>` existing when `setup(...)` is invoked. 
However, if you just do this:

```python
class TomoPyExtension(Extension):
    def __init__(self, name, sourcedir=''):
        Extension.__init__(self, name, sources=[])
        self.sourcedir = os.path.abspath(sourcedir)

class TomoPyBuild(build_ext, Command):

    def run(self):
        for ext in self.extensions:
            self.build_extension(ext)

    def build_extension(self, ext):
        sp.check_call((sys.executable, 'build.py'))

setup(
    # ... etc.
    ext_modules=[TomoPyExtension('libtomopy')],
    cmdclass=dict(build_ext=TomoPyBuild),
    # ... etc.
)
```
the installation does not include `libtomopy.<ext>` regardless of the `MANIFEST.in` setting. This is not a "bug" -- I explained why this happens previously.

The reason I propose the latter as opposed to the former is that the latter allows for customization via the traditional `setup.cfg`:

```python
[build_ext]
# options
```

- These modifications make it such that TomoPy conforms to standard ways of doing things -- not doing so is, in my opinion, an unnecessary design choice. 
    - There doesn't seem to be a reason for not supporting `python setup.py build_ext` if the user wants to do this. 
    - In fact, doing so, maintains backward-compatibility because this was something that used to be done in the `.travis.yml` file, which I always prefer as a guide for testing since this is pretty much guaranteed to be up-to-date as opposed to the documentation! 
    - One should always strive for backwards-compatibility because it is not at all uncommon for users and developers to have a set of scripts that will be broken by failure to maintain backwards-compatibility.
- Ideally, a package should contain a log of the settings used to build the package
    - A setup/configuration log is extremely helpful when addressing both performance issues and bug reports 
        - For example, when an issue is filed on GitHub, all you have to say is please attach `setup.log` from your package, and you can determine how exactly the package was installed and can thus more easily reproduce the issue
    - For TomoPy, this could easily be done by generating a `setup.log` and including this in the installation. The easiest and more reliable way to do this, in my opinion, is to copy `setup.cfg` to `setup.log` and append any customizations to that file, logging the git revision, the compiler, etc.
- Allowing options/customizations is important, especially for HPC. 
    - These customization will come more into play down the road when TomoPy integrates some performance and capability extensions that will not be universally supported

In the end, this minor revision to `setup.py` is part of a long-term strategy that has to do with revisions to TomoPy that I have discussed with @dgursoy. Many of these extensions will require reworking of the build system to ensure that `python setup.py install` or `python -m pip install .` is transparent to the user and just simply "works" but on the back-end queries the system extensively to determine what is supported by the system (e.g. OpenMP, OpenACC, CUDA, MPI, etc.) and then builds TomoPy with the available extensions and optimizations. 

Here is a list of some of the planned extensions:

1) Enable SIMD with OpenMP (e.g. `#pragma omp simd`) -- this requires compiler flags that are not supported by all compilers.
2) We are working on GPU implementations with variants using CUDA, OpenACC, and OpenMP of the iterative algorithms
    - We may not end up using all of these -- this is an exploration by NERSC w.r.t. performance vs. maintainability and complexity
3) MPI Parallelism
    - TomoPy reconstructions support `chunks` so that the reconstructions fit into memory. When dealing with multiple nodes in HPC, I will be working on modifying the chunk parameter to partition chunks across the number of available nodes since each node has it's own memory space.
4) Threading at the python level could be replaced with a better system within the compiled code -- I won't go into detail but there are better ways than how threading is currently implemented

I hope reviewing this list makes it clear why using CMake to generate Makefiles is much more desirable than standard Makefiles and in the end, because we will have these different build variants, we need to support customization in `setup.cfg` which, the revisions to `setup.py` provide.

**Comment by jrmadsen** [comment] 2018-11-05 20:54
Note: when testing this out, do not issue any `python build.py` commands. This is completely against the purpose of my modifications to `setup.py` -- this is an unusual step in the standard process of installing a Python package. The entire idea is to remove having to directly use this command.

Add one of those modifications to `setup.py` and either run `python setup.py install` or `python -m pip install .` (and make sure that you have removed any pre-existing `tomopy/sharedlibs/libtomopy.*` along with any previous installations).

**Comment by carterbox** [comment] 2018-11-06 01:32
Here is what I am understanding: We could add
```python
import subprocess as sp
sp.check_call((sys.executable, 'build.py'))

setup(...
```
to `setup.py` in order to install everything correctly in one step, but you want to instead ask `setuptools` to call `build.py` using a custom `Extension` because it allows you to use [`setup.cfg`](https://docs.python.org/3/distutils/configfile.html) to pass parameters to `setuptools` to pass parameters to CMake. The unfortunate side effect is that you have to manually find and copy `libtomopy.<ext>` to the installation directory after it is built because `ext_modules` doesn't respect `MANIFEST.in` because we're using Make instead of `setuptools` to run the compiler.

I totally understand why using CMake in the future is desired. I support it. :smiley: No need for further justification for that. The missing link for me is why using CMake requires parameters to be passed from `setup.cfg` through `setuptools`. Isn't it easier to set CMake parameters directly? Is it because you want to call `python setup.py build_ext --options` instead of `python build.py --options`?

**Comment by newville** [comment] 2018-11-06 02:43
@carterbox  Sorry, I should have been clearer.   I used  "clever" to suggest "tries to be smart, and sometimes fails".  Sometimes "dumb" (obvious, simple, brute-force) is the better way to go.   

I do agree that `python setup.py install` should be an expected installation method, and that it probably should be preferred over both `pip install .` and over  `python build.py && python setup.py install`.  But that does not mean that the "build libtomopy" step should be a `setuptools.Extension`.  That caused serious problems that were only solved recently, and led to the existence of a separate `build.py`.  Incorporating or using code from `build.py` into `setup.py` would be fine, but using `setuptools.Extension` would be unfortunate.  The current master shows that is not necessary, and the proposed solution shows it would add a significant amount of code to make `Extension` cleverly(!) hide that fact that it is not actually an extension. 

@jrmadsen  yes, I was (and still am) comparing to master branch, as would be typical for reviewing a PR.  The master branch is not broken. 

Again, I have no objections to the planned changes to incorporate other ways to compile libtomopy.  But that does not make libtomopy an Extension.  It is independent of Python's setuptools, and should not be built by it.  Doing so has caused real problems.

> These modifications make it such that TomoPy conforms to standard ways of doing things 
> -- not doing so is, in my opinion, an unnecessary design choice.

I would have no objection to incorporating more of `build.py` into `setup.py`.  I am not fond of it being a separate step.  But, it does actually work, and "actually working" is actually pretty important.  The first rule is always "do no harm". 

> There doesn't seem to be a reason for not supporting `python setup.py build_ext` if the 
>  user wants to do this.

Calling libtomopy an extension does not make it one, and has caused problems in the recent past.

> Ideally, a package should contain a log of the settings used to build the package

Does tomopy have one of those now?  Will one be created?   I don't see that in any PR.  Maybe I missed it.

> allowing options/customizations is important, especially for HPC.
> These customization will come more into play down the road when TomoPy integrates some 
> performance and capability extensions that will not be universally supported

Wouldn't those need to be determined when building the shared library instead of at install time?  I agree with @carterbox that such changes in compiler options would be better done through options to `build.py` (or equivalent code used in `setup.py`) rather than as a `setuptools.Extension`.

**Comment by jrmadsen** [comment] 2018-11-06 06:20
@newville I don't think you understand `setuptools.Extension`. I explained how TomoPy is, in fact, an extension in another thread. It has nothing to do with `Python.h`, it simply has to do with creating bindings to access a compiled library from Python. Please find that thread and read it. Using `setuptools.Extension` is not changing how TomoPy is compiled AT ALL. **I am not modifying the build procedure whatsoever.** I am using `setuptools.Extension` to get a directory path and copying libtomopy into that directory path -- nothing more. Please stop worrying that I am going to somehow break your Windows builds -- I have far more experience in ensuring cross-platform portability than you realize. 

@carterbox I use the options to configure the CMake command. There are other ways with `scikit-build` but I found that something like below is the most portable (the `cmake` python package is more widely available than `scikit-build` -- at least when I first starting doing this a year or two back)

example `setup.cfg`:

```python
[build_ext]
build_type=Release
```

example `setup.py`:

```python
        # append the options
        cmake_args += [ '-DCMAKE_BUILD_TYPE={}'.format(self.build_type) ]

        # this overrides -DCMAKE_BUILD_TYPE=... (I just used the above as an example)
        build_args = [ '--config', self.build_type ]

        if platform.system() == "Windows":
            # Windows requires specify arch and target, /m for parallel build
            if sys.maxsize > 2**32 or platform.architecture()[0] == '64bit':
                  cmake_args += ['-A', 'x64']
            build_args += ['--target', 'ALL_BUILD', '--', '/m' ]
        else:
            # parallel build with Makefiles
            import multiprocessing as mp
            nproc = '-j{}'.format(mp.cpu_count())
            build_args += [ '--', nproc ]

        # configure the project
        subprocess.check_call(['cmake'] + cmake_args + [ ext.sourcedir ],
                              cwd=self.build_temp, env=env)

        # build the project
        subprocess.check_call(['cmake', '--build', self.build_temp] + build_args,
                              cwd=self.build_temp, env=env)

```

**Comment by carterbox** [comment] 2018-11-06 17:05
@jrmadsen Is the following correct? The reason you made a custom `Extension` is so you can install on one line using `setup.cfg` to pass arguments to CMake. Building using CMake doesn't require a custom `Extension`, but if you want to use CMake and `setup.cfg`, it requires replacing the default build system from `disuitls`.

:slightly_frowning_face: I'm still miffed that we need to manually copy the shared library. This tells me that we are using `ext_modules` in a way that wasn't intended, :thinking: but I supposed that's because we want the convenience of using `setup.cfg`.

:thinking: Is it worth revisiting `scikit-build` to lower maintenance costs inside `tomopy`? This package is available on `conda-forge`, our default package channel for `tomopy`. It's also only a build dependency, so most of our users (who download via conda) wouldn't be affected.

**Comment by jrmadsen** [comment] 2018-11-06 19:10
Using CMake does require Extension. We can have the discussion about scikit-build another time. I avoided doing it because I encountered portability issues when I used it, especially when I was testing installation with pip -- it may work for you locally but I encountered issues on other Linux systems, either CentOS or OpenSUSE. I can test again. 

We need to copy the shared library manually because of y'all's non-standard build system! I understand why y'all are doing it but when y'all build the library, build.py is placing the library in a non-standard location. If you actually look at my build_ext, you will see `self.get_ext_fullpath(ext.name)` -- it is something built into build_ext. That path is the standard location that extensions are placed in when they are built, and by being placed there, they get installed -- I only have to copy over to that directory because of the aforementioned reasons regarding libtomopy existing and bc you do not place the compiled library in the location that setuptools expects you to put compiled extensions. In other words, I am actually using build_ext properly but I am copying instead of building in order to work with your implementation (NOTE: while commonly used, build_ext doesn't have to use the Python setuptools build system -- it can call autotools, CMake, make, ninja, etc.)

**Comment by carterbox** [comment] 2018-11-06 19:57
I always thought we were putting the shared library into a weird place, but I couldn't figure out where else to put it so it would be installed for non-development distributions. Where is the standard place? I scoured python module building documentation, but they don't explain much about including binaries with packages. Why don't we just change where `build.py` places the shared library (to the standard location), then we don't have to do a copying operation?

**Comment by jrmadsen** [comment] 2018-11-07 00:41
If you run `python setup.py build` (with my revisions) look in the build folder that gets generated. There are typically a couple directories that get generated and the all have suffixes that are specific to the platform (i.e. OS, CPU arch, Python implementation, and version) which is why I use build_ext bc the folder name is complicated. The `build/lib.<...>` folder is essentially where I am copying to. The contents and layout of this folder are what gets installed by setuptools or pip.  

There is a benefit to leaving it as it is right now with regard to testing. If you didn't install to ^/tomopy/sharedlibs/libtomopy.<ext>, when you ran coverage/nosetests, they would all fail bc the tomopy folder in $PWD would get interpreted as the path for `import tomopy` and since the shared library is not there, nothing works. 

As far as docs go, I've found the documentation to be terrible also. I just figured it out through trial-and-error, print statements, man pages, and rooting through the actual scripts provided by the modules.

**Closed** 2018-12-12 19:08 UTC
Labels: enhancement
