### ISSUE TITLE
Cannot install using windows Conda

### ISSUE THREAD

**Issue by xianbo** [tomopy/tomopy#219] opened 2016-07-18 22:44 UTC
I shows an error: Package missing in current win-64 channels.

**Comment by tomopy** [comment] 2016-07-19 00:00
Currently only linux and OSX are actively maintained. If some windows developer reads this perhaps can help

Sent by T-mobile

**Comment by teracamo** [comment] 2017-06-29 02:39
If you are interested in using windows, visit my fork branch win_x64 as I am not able to test my build on linux

**Comment by carterbox** [comment] 2018-08-24 16:59
Duplicate of #283

**Closed by carterbox** 2018-08-24 16:59 UTC
Labels: Windows
