### ISSUE TITLE
Alternate reconstruction methods do not complete.

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#120] opened 2015-08-27 20:47 UTC
Ubuntu 15.04 / conda tomopy 0.1.11 / AMD processor

I was trying to test different reconstruction methods to compare the results:

```
for algo in ['gridrec', 'mlem', 'osem', 'pml_hybrid', 'ospml_hybrid']:
        rec = tomopy.recon(proj, theta, center=1274.2, algorithm=algo, emission=False)
        print algo + " reconstruction complete"

        tomopy.io.writer.write_tiff_stack(rec, fname='./recon_test/' + algo)
        print algo + " SAVED!"
```

Here is the output.

```
carterbox@COMPY:$ python new_tomopy_script.py
phase retreval complete
gridrec reconstruction complete
gridrec SAVED!
mlem reconstruction complete
mlem SAVED!
```

Everything works as expected until the workers all finish doing their parts of the 'osem' reconstruction. After their processors usage drops to zero, the workers are never deallocated. They just sit there indefinitely with CPU usage at zero. The same happens for both of the above hybrid methods as well.

When I try and interrupt the process using ^C it looks like all the workers are waiting for more tasks. Here is an abbreviated list of the traceback from the interrupt. Also, after using ^C to interrupt the process, new workers are created to replace the ones that were killed.

```
^CProcess PoolWorker-56:
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run self.run()
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/queues.py", line 378, in get
    self.run()
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/local/anaconda/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
```

Is there a debug mode for tomopy? Since I updated from the legacy version, there seems to be no terminal output as things progress.

**Comment by dakefeng** [comment] 2015-08-27 20:50
can you try taking out the setting for center?

**Comment by carterbox** [comment] 2015-08-28 01:18
Removing the center specification doesn't work.

**Comment by tomopy** [comment] 2015-08-28 03:00
I have to retest this. I feel that there may be something wrong with the python multiprocessing but not sure yet. What is the data shape, and how many cores you have? Some combinations may trigger this. I would try giving various ``num_core`` values to see if it originates from a specific value. Also I wonder if the algorithms work as desired when run independently (i.e. without in a for loop)?

Regarding debugging, you are right. This one has no debugging option yet. We should definitely do this soon but not sure when. I'll open an independent issue for this.

**Comment by carterbox** [comment] 2015-08-28 22:59
**dataset:** 1500 scans around 180 degrees. I'm only processing sinograms [0, 64] to speed things up.
**available cores:** 12

`ncore=0` Throws an error. Maybe it should be caught and automatically bump ncore up to 1 instead?
````
Traceback (most recent call last):
  File "new_tomopy_script.py", line 77, in <module>
    rec = tomopy.recon(proj, theta, algorithm=algo, emission=False, ncore=0)
  File "/usr/local/anaconda/lib/python2.7/site-packages/tomopy/recon/algorithm.py", line 244, in recon
    tomo, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
  File "/usr/local/anaconda/lib/python2.7/site-packages/tomopy/recon/algorithm.py", line 299, in _dist_recon
    nchunk=nchunk)
  File "/usr/local/anaconda/lib/python2.7/site-packages/tomopy/util/mproc.py", line 115, in distribute_jobs
    nchunk = (ndim - 1) // ncore + 1
ZeroDivisionError: integer division or modulo by zero
````
`ncore=1` Stalls / `ncore=4` Stalls / `ncore=8` Stalls / `ncore=12` Stalls

Also, I noticed that ncore+1 processes are created. If you run the script with `ncore = 1`, then there are 3 python processes running when `recon` starts. 2 are idle and 1 is doing all the work.

**Comment by tstannar** [comment] 2015-09-03 18:16
I have noticed a similar problem with gridrec. For instance, when I am running the reconstructions of 1500 projections at 2560x2160 pixels, I am only able to do 200 slices with Hyperthreading on or 300 slices with hyperthreading off. The computer is a 10 core Xeon with 126 gb ram. If too many slices are used, the python processes all go to sleep after the first chunk is done instead of writing the slices to the hard drive.

**Comment by dgursoy** [comment] 2015-09-09 16:10
I created a dummy data and tried to reconstruct it:
```
import tomopy
import numpy

prj = numpy.ones((1500, 300, 2560), dtype='float32')
ang = tomopy.angles(prj.shape[1])
rec = tomopy.recon(prj, ang, algorithm='gridrec', ncore=12)
```
Here's some more observations: Python creates 12 worker, and 2 helper processes. One of the helper processes (Waiting channel: futex_wait_queue_me) is responsible for the data transfer, because it starts with the consumed memory of 11.2 GiB and the memory allocation is reduced gradually. Once it hits 0 GiB, then the script ends. Each worker processes are fixed to 130 MiB independent of the data size (why?). Could you please check if you can observe a similar mechanism when it hangs?

**Comment by tstannar** [comment] 2015-09-15 16:44
I just set it up with hyperthreading off. Ten cores in the processor, I let tomopy decide the number of cores on its own. 1500proj x 400 slices x 2560 , I saw 12 python processes, ten workers which have varied values until the processor reaches 100% duty cycle, then stabilize at 132.7 MiB for all except 2 which continued to change to higher values, and two helpers, futex_wait_queue_me reaches 17.4 GiB, then goes to zero as it writes the data to disk, once the chunk is done the processes all go to sleep and the script stops. I have to close the terminal to stop them. Trying to continue them in the system monitor doesn't work.

**Comment by dmpelt** [comment] 2015-10-15 11:24
I get similar problems with the `sirt` method. It is very reproducible when running inside an IPython `%timeit` magic call, which causes a hang every time I run it. Sample code (for in an IPython interactive terminal):

    import tomopy
    import numpy as np
    ang = tomopy.angles(1024)
    prj = np.zeros((1024,1,1024),dtype=np.float32)
    %timeit tomopy.recon(prj,ang,method='sirt',num_iter=1)

This hangs, and I have to kill the parent ipython process to regain control of the terminal. 

I think the following might be happening: if something causes the child process to crash (segfault or something), the thread pool is unable to recover and hangs. I see topics with similar problems on the internet. In Python 3 this is fixed in the `concurrent.futures` module, and for `multiprocessing` it is possible to continually check the child processes for crashes (see [here](http://stackoverflow.com/questions/24370930/multiprocessing-pool-hangs-if-child-causes-a-segmentation-fault)), but it is probably the easiest (and best) to fix the crashes of the child process.

Indeed, I found out that the above code causes a coredump on my machine, which shows that a segfault occured in line 253 of `src/utils.c`. The relevant `gdb` output is:

    (gdb) where
    #0  0x00007fa1af099cb2 in calc_simdata (p=p@entry=400, s=s@entry=0, c=c@entry=92, ry=ry@entry=1024, rz=rz@entry=1024, num_slices=num_slices@entry=1, num_pixels=1024, csize=950, indi=0x312a7e0, dist=0x31287d0,
    model=0x7fa1ac699000, simdata=0x39123d0) at src/utils.c:253
    #1  0x00007fa1af0a5b17 in sirt (data=0x7fa1ebbc0000, dx=1024, dy=1, dz=1024, center=0x7fa1af4236e4, theta=0x3118734, recon=0x7fa1ac699000, ngridx=1024, ngridy=1024, num_iter=1, istart=0, iend=1) at src/sirt.c:137
    .... (lots of lines)

I don't know anything about the specific `sirt` implementation, so I am afraid that I have no idea where to start to fix this bug, but I hope this information helps!

As for the general problem, maybe the other methods cause a segfault in some cases as well, which will result in a hanging process pool.

**Comment by dgursoy** [comment] 2015-12-23 01:57
Any updates on this one after the new release?

**Comment by tstannar** [comment] 2016-01-14 01:16
I tried the 0.1.5 release with python 3.5 on the same machine, 1500 proj x 740 slices x 2560 wide and 1500x560x2560.

The first time the system exited on its own, saying insufficient memory. I'm not sure if this was a ram issue or something else. The system uses 17.4 gb for 290 slices so I don't believe it would have needed much more than 44.4 gb ram, assuming linear scaling? 

The second time the python processes appeared to sleep before reconstruction started, since the ram value hadn't stabilized yet and the duty cycle on all the cores didn't reach 100% for a significant time period.

Additionally, the ram seems to jump during memory allocation. It jumps about 20% over what it needs, then stabilizes at a lower value after a few seconds.

The system still runs fine with < 300 slices/chunk.

**Comment by dmpelt** [comment] 2016-01-14 08:35
I think the underlying cause (that any error in the C code will lead to a hang in the thread pool) is not fixed yet. I don't know whether there is a nice solution for this, but I guess it would be better if it will throw some exception with a useful message instead of causing a hang. I will look into this.

**Comment by xianghuix** [comment] 2016-03-09 20:11
Is there any progress on fixing this bug? The hanging issue occurs so often these days. It prevents batch processing. It even causes interruption for the processing of a large data set. this is a critical issue otherwise users cannot take advantage of latest developments in tomopy.

**Comment by dgursoy** [comment] 2016-03-09 20:14
#162 may resolve some aspects of the problem. We're working on this.

**Comment by xianghuix** [comment] 2016-03-09 20:18
I updated to the latest version but it seems the hanging issue still there. I suppose the patch from #162 kill the process if hanging happens, right?

Thanks,

Xianghui
________________________________

**Comment by dgursoy** [comment] 2016-03-09 20:23
Yes, but this is not yet released (even merged). #162 is rather a large PR that needs some additional care before we merge. You probably mentioned #160, where Daniel introduced a checker to kill hanging processes. But this one is not released in the Conda distribution yet (as I can recall), but you can try it by cloning and installing from the GitHub master branch.

**Comment by dgursoy** [comment] 2016-04-07 15:03
Any updates on this issue after new PRs?

**Comment by tstannar** [comment] 2016-06-14 18:55
With Tomopy 1.0.0 installed via conda, the code does not hang when using over 290 slices, but it does not complete either. Instead for the same type of data set, it loads all the data then when the reconstruction starts I get 
OSError: Insufficient memory on device.
and the code exits.
I'm not sure which type of memory is being referred to since I was only using 34 of 128 gb of ram on the system.

On another note, when I do use small chunks and the reconstructions complete, or when I do centering, the grayscale values are much different than before. It seems like the -log is not being taken any more since multiplying by -1 makes the data appear more similar to previous reconstruction results.

**Comment by dgursoy** [comment] 2016-06-14 19:01
It could be because numpy complains about the array allocation, before actually trying to do it, and throws you an error. Could you monitor your memory consumption while reconstructing, let's say 128 slices, and check how much memory is being eaten in reconstruction part?

With 1.0.0 we stopped using emission argument in reconstruction. Please try either:
```
prj = tomopy.minus_log(prj)
```
or,
```
prj = -numpy.log(prj)
```
before projection. But since it's a logarithm operator, please make sure that the data doesn't contain minus values (you can simply take absolute value or ignore the negative values).

**Comment by tstannar** [comment] 2016-06-14 19:14
Ok, for 128 slices (128,2560,2560, 32 bit) it appears the ram devoted to performing reconstruction was 3.3 GB. 
Also, taking the absolute value and -log took care of the image appearance. Thanks.

**Comment by dgursoy** [comment] 2016-06-14 19:16
Nice. Have you checked how much peak memory did it use for processing 128 slices?

**Comment by dmpelt** [comment] 2016-06-15 15:07
I have had similar ` OSError: Insufficient memory on device.` errors before on our machines, and was planning to create a issue for it. I think the problems are related to the fact that the `multiprocessing` module might be using `/tmp/` to store data that is shared between processes. For example, on a machine we have, there is 128GB RAM installed, but `/tmp/` only has 2 GB available. I start getting the `OSError` with arrays larger than 768x768x768, or about 1.8GB, which is around the space available on `/tmp`. This is the output of `df -h /tmp` during a run with a 768x768x768 array:

```bash
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  3.2M  1.8G   1% /tmp
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  1.5G  369M  80% /tmp
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  1.7G  155M  92% /tmp
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  1.7G  103M  95% /tmp
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  1.8G  2.7M 100% /tmp
$ df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       2.0G  1.8G     0 100% /tmp
```
And the script crashes with the `OSError`.

I don't know what a good solution for this problem is... I am not the biggest fan of the `multiprocessing` module, since it causes all kinds of hard-to-debug problems (although it has been better in later Python versions). Also, maybe the use of `/tmp/` as temporary storage is actually quite costly in terms of computation time for large arrays. So maybe it is possible to change to the `threading` module instead? By dropping the Python GIL in C code, you can get very good performance, but it may require rewriting some parts of TomoPy.

**Comment by dmpelt** [comment] 2016-06-15 15:52
Small update: it seems that the `TMPDIR` environment variable can be used to specify the directory that `multiprocessing` uses as temporary storage. So if I change `TMPDIR` to somewhere in my homedir (which has 1.5TB free space), the script completes without an error, even for larger arrays. However, it will still create a large file on disk, so it might still be a good idea to find a more permanent solution to this.

**Comment by tstannar** [comment] 2016-07-20 16:58
For 128 slices the reconstruction uses 4.6 gb ram and holds constant for most of the reconstruction without going over 4.6 gb.

**Closed** 2017-10-25 22:51 UTC
Labels: bug
